version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      babel:
        patterns:
          - '*babel*'
      workbox:
        patterns:
          - 'workbox-*'
      stylelint:
        patterns:
          - 'stylelint*'
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
      webpack:
        patterns:
          - '*webpack*'
      material:
        patterns:
          - '@material/*'
