dist: bionic
language: node_js
node_js:
  - "12"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script: npx firebase use abraham-d3850
script:
  - npm run lint
  - npm run test
