name: Update tweets
on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
jobs:
  tweets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run get-tweets
      - run: npm run build
      - uses: w9jds/firebase-action@v11.9.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: abraham-d3850
