name: Update tweets
on:
  schedule:
    - cron: '0 * * * *'
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
jobs:
  tweets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run get-tweets
      - run: npm run build
      - uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: abraham-d3850
